# Generated by Django 4.0.5 on 2022-08-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payinfo',
            old_name='OrderInfoMerchantTradeNo',
            new_name='OrderInfoMerchantOrderNo',
        ),
    ]
