# Generated by Django 4.0.1 on 2022-06-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=100, unique=True)),
                ('time_type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkupItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.case')),
                ('cityarea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.cityarea')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hourly_wage', models.IntegerField(blank=True, default=0, null=True)),
                ('halfday_wage', models.IntegerField(blank=True, default=0, null=True)),
                ('oneday_wage', models.IntegerField(blank=True, default=0, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.cityarea')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.servant')),
            ],
        ),
        migrations.CreateModel(
            name='ServantSkillShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.languageskill')),
            ],
        ),
        migrations.CreateModel(
            name='ServantMarkupItemShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.markupitems')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant')),
            ],
        ),
        migrations.CreateModel(
            name='ServantLicenseShipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=modelCore.models.image_upload_handler)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.license')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='modelCore.servant')),
            ],
        ),
        migrations.CreateModel(
            name='ServantCategoryShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.category')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.servant')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('disease', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_info', models.CharField(blank=True, max_length=255, null=True)),
                ('conditions_info', models.CharField(blank=True, max_length=255, null=True)),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.bodyconditions')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PaymentType', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('MerchantID', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoMerchantTradeNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoTradeDate', models.DateTimeField(null=True)),
                ('OrderInfoTradeNo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('OrderInfoTradeAmt', models.IntegerField(default=0, null=True)),
                ('OrderInfoPaymentType', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('OrderInfoChargeFee', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('OrderInfoTradeStatus', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoBankCode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfovAccount', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('ATMInfoExpireDate', models.DateTimeField(null=True)),
                ('CVSInfoPayFrom', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentNo', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CVSInfoPaymentURL', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CardInfoAuthCode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('CardInfoGwsr', models.IntegerField(default=0, null=True)),
                ('CardInfoProcessDate', models.DateTimeField(null=True)),
                ('CardInfoAmount', models.IntegerField(default=0, null=True)),
                ('CardInfoCard6No', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('CardInfoCard4No', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.case')),
            ],
        ),
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_score', models.IntegerField(blank=True, default=0, null=True)),
                ('customer_content', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_review_createdate', models.DateTimeField(blank=True, null=True)),
                ('servant_score', models.IntegerField(blank=True, default=0, null=True)),
                ('servant_content', models.CharField(blank=True, max_length=255, null=True)),
                ('servant_review_createdate', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.recipient'),
        ),
        migrations.AddField(
            model_name='order',
            name='servant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.serviceitems'),
        ),
        migrations.AddField(
            model_name='case',
            name='cityarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.cityarea'),
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='service_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.serviceitems'),
        ),
    ]
