# Generated by Django 4.0.5 on 2022-06-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='Consult_all_servant',
            new_name='consult_all_servant',
        ),
    ]
