# Generated by Django 4.0.5 on 2022-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlanguage',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
