# Generated by Django 4.0.5 on 2022-06-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlicenseshipimage',
            name='is_upload_image',
            field=models.BooleanField(default=False),
        ),
    ]
