# Generated by Django 4.0.5 on 2022-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantskill',
            name='languageSkill',
            field=models.CharField(max_length=100),
        ),
    ]
