# Generated by Django 4.0.5 on 2022-07-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
