# Generated by Django 4.0.5 on 2022-09-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_passed',
        ),
    ]
