# Generated by Django 4.0.5 on 2022-06-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_rename_consult_all_servant_case_consult_all_servant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant', to='modelCore.servant'),
        ),
    ]
