# Generated by Django 4.0.5 on 2022-09-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_remove_user_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempcase',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempcase',
            name='road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
