# Generated by Django 4.0.5 on 2022-08-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_rename_orderinfomerchanttradeno_payinfo_orderinfomerchantorderno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='servant_avg_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
