# Generated by Django 4.0.5 on 2022-06-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_userlicenseshipimage_is_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servantlicenseshipimage',
            name='is_upload_image',
            field=models.BooleanField(default=False),
        ),
    ]
