# Generated by Django 4.0.5 on 2022-06-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_alter_servantskill_languageskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServantServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.serviceitem')),
            ],
        ),
    ]
