# Generated by Django 4.0.5 on 2022-06-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_case_servant'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='care_type',
            field=models.CharField(choices=[('home', '居家照顧'), ('hospital', '醫院看護')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='is_alltime_service',
            field=models.BooleanField(default=False),
        ),
    ]
