# Generated by Django 4.0.5 on 2022-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_rename_rating_user_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_continuous_end_time',
            field=models.FloatField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_continuous_start_time',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
