# Generated by Django 4.0.5 on 2022-06-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_servantserviceitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServantServiceItem',
            new_name='ServantServiceItemShip',
        ),
    ]
