# Generated by Django 4.0.5 on 2022-07-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_case_city_alter_order_user_alter_review_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
