# Generated by Django 4.0.5 on 2022-07-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_alter_case_end_time_alter_case_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Branch_Financial_Institutions_Code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Financial_Institutions_Code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
