# Generated by Django 4.0.5 on 2022-06-28 06:26

from django.db import migrations, models
import modelCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_servantlicenseshipimage_is_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=modelCore.models.image_upload_handler),
        ),
    ]
