# Generated by Django 4.0.5 on 2022-08-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_user_is_continuous_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='servant_avg_rating',
        ),
    ]
