# Generated by Django 4.0.5 on 2022-07-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_license_remark_service_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='is_alltime_service',
            new_name='is_continuous_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_alltime_service',
            new_name='is_continuous_time',
        ),
    ]
