# Generated by Django 4.0.5 on 2022-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_user_branch_financial_institutions_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userserviceship',
            name='increase_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
