# Generated by Django 4.0.5 on 2022-08-16 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0005_remove_user_avg_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicenseshipimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userserviceship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='services', to=settings.AUTH_USER_MODEL),
        ),
    ]
