# Generated by Django 4.0.5 on 2022-07-06 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0005_rename_is_alltime_service_case_is_continuous_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicelocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='city_locations', to='modelCore.city'),
        ),
        migrations.AlterField(
            model_name='userservicelocation',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='county_locations', to='modelCore.county'),
        ),
        migrations.AlterField(
            model_name='userservicelocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
