# Generated by Django 4.0.5 on 2022-09-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0005_user_apple_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fcm_notify',
            field=models.BooleanField(default=True),
        ),
    ]
