# Generated by Django 4.0.5 on 2022-07-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0005_userserviceship_increase_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Branch_Financial_Institutions_Code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Financial_Institutions_Code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accounts',
        ),
        migrations.AddField(
            model_name='user',
            name='ATMInfoAccount',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ATMInfoBankCode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ATMInfoBankInstitutionCode',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
