# Generated by Django 4.0.5 on 2022-07-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_remove_user_branch_financial_institutions_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ATMInfoBankInstitutionCode',
            new_name='ATMInfoBranchBankCode',
        ),
    ]
