# Generated by Django 4.0.5 on 2022-08-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_alter_userlicenseshipimage_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebodyconditionship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_body_conditions', to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='casediseaseship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_diseases', to='modelCore.case'),
        ),
    ]
