# Generated by Django 4.0.5 on 2022-09-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_rename_message_chatroommessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hours_half_day_work',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hours_hour_work',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hours_one_day_work',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wage_half_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wage_hour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='wage_one_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
