# Generated by Django 4.0.5 on 2022-08-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_alter_casebodyconditionship_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseserviceship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_services', to='modelCore.case'),
        ),
    ]
