# Generated by Django 4.0.5 on 2022-07-06 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0007_alter_userweekdaytime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicelocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.city'),
        ),
        migrations.AlterField(
            model_name='userservicelocation',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.county'),
        ),
    ]
