# Generated by Django 4.0.5 on 2022-07-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0008_alter_userservicelocation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweekdaytime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_weekday', to=settings.AUTH_USER_MODEL),
        ),
    ]
