# Generated by Django 4.0.5 on 2022-08-22 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0008_alter_caseserviceship_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ship_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
