# Generated by Django 4.0.5 on 2022-08-23 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_alter_userserviceship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_messages', to='modelCore.chatroom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_orders', to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='orderincreaseservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_increase_services', to='modelCore.order'),
        ),
        migrations.AlterField(
            model_name='orderweekday',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_weekdays', to='modelCore.order'),
        ),
        migrations.AlterField(
            model_name='userlanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_languages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlicenseshipimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_license_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
