# Generated by Django 4.0.5 on 2022-06-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_alter_order_end_date_alter_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantmarkupitemprice',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
