# Generated by Django 4.0.5 on 2022-07-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_alter_userweekdaytime_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='end_time',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='start_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='weekday',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='end_time',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weekday',
            field=models.CharField(blank=True, choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1, null=True),
        ),
    ]
