# Generated by Django 4.0.5 on 2022-07-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_remove_chatroom_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='emergencycontact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='emergencycontact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='emergencycontact_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
