# Generated by Django 4.0.5 on 2022-07-07 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_case_end_time_case_start_time_case_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='weekday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='order',
            name='weekday',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
