# Generated by Django 4.0.5 on 2022-08-23 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_alter_message_chatroom_alter_order_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_reviews', to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_reviews', to='modelCore.order'),
        ),
    ]
