# Generated by Django 4.0.5 on 2022-09-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0009_remove_order_hours_half_day_work_and_more'),
        ('modelCore', '0010_alter_order_user'),
    ]

    operations = [
    ]
