# Generated by Django 4.0.5 on 2022-07-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_case_emergencycontact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
