# Generated by Django 4.0.5 on 2022-06-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0010_alter_servantmarkupitemprice_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cityarea',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='order',
            name='servant',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_time',
        ),
        migrations.AddField(
            model_name='case',
            name='servant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant'),
        ),
        migrations.AddField(
            model_name='order',
            name='createdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderServiceItemShip',
        ),
    ]
