# Generated by Django 4.0.5 on 2022-08-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_alter_review_case_alter_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.CharField(choices=[('unTaken', '未承接'), ('unComplete', '未完成'), ('Complete', '已完成'), ('Canceled', '取消'), ('endEarly', '提早結束')], default='unTaken', max_length=10),
        ),
    ]
