# Generated by Django 4.0.5 on 2022-09-26 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_merge_20220926_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servant_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
