# Generated by Django 4.0.5 on 2022-06-20 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_remove_order_cityarea_remove_order_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderreview',
            old_name='customer_content',
            new_name='user_content',
        ),
        migrations.RenameField(
            model_name='orderreview',
            old_name='customer_review_createdate',
            new_name='user_review_createdate',
        ),
        migrations.RenameField(
            model_name='orderreview',
            old_name='customer_score',
            new_name='user_score',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='servant',
            old_name='halfday_wage',
            new_name='home_halfday_wage',
        ),
        migrations.RenameField(
            model_name='servant',
            old_name='hourly_wage',
            new_name='home_hourly_wage',
        ),
        migrations.RenameField(
            model_name='servant',
            old_name='oneday_wage',
            new_name='home_oneday_wage',
        ),
        migrations.RenameField(
            model_name='servantmarkupitemprice',
            old_name='price',
            new_name='pricePercent',
        ),
        migrations.RenameField(
            model_name='servantskillship',
            old_name='skill',
            new_name='languageSkill',
        ),
        migrations.RemoveField(
            model_name='servant',
            name='name',
        ),
        migrations.AddField(
            model_name='servant',
            name='hospital_halfday_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='hospital_hourly_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='hospital_oneday_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='servant',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_servant',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserLicenseShipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=modelCore.models.image_upload_handler)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.license')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
