# Generated by Django 4.0.5 on 2022-07-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_order_servant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebodyconditionship',
            name='body_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.bodycondition'),
        ),
        migrations.AlterField(
            model_name='casebodyconditionship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='casediseaseship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='casediseaseship',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.diseasecondition'),
        ),
        migrations.AlterField(
            model_name='caseserviceship',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.case'),
        ),
        migrations.AlterField(
            model_name='caseserviceship',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelCore.service'),
        ),
    ]
