# Generated by Django 4.0.5 on 2022-07-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0011_alter_case_servant_alter_case_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorkDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=8, null=True)),
                ('start_time', models.IntegerField(blank=True, default=0, null=True)),
                ('end_time', models.IntegerField(blank=True, default=24, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.order')),
                ('servant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant_workdays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CaseWeekDayTime',
        ),
    ]
