# Generated by Django 4.0.5 on 2022-06-20 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_rename_customer_content_orderreview_user_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servant',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
