# Generated by Django 4.0.5 on 2022-08-28 00:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_case_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('state', models.CharField(choices=[('draft', 'draft'), ('publish', 'publish')], max_length=10)),
                ('create_date', models.DateField()),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostCategoryShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ship_posts', to='modelCore.blogcategory')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ship_categories', to='modelCore.blogpost')),
            ],
        ),
    ]
