# Generated by Django 4.0.5 on 2022-07-25 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_alter_casebodyconditionship_body_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
