# Generated by Django 4.0.5 on 2022-07-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_orderworkdate_delete_caseweekdaytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='weekday',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
