# Generated by Django 4.0.5 on 2022-09-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0012_alter_review_servant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='county',
        ),
        migrations.RemoveField(
            model_name='tempcase',
            name='county',
        ),
        migrations.RemoveField(
            model_name='userservicelocation',
            name='county',
        ),
    ]
