# Generated by Django 4.0.5 on 2022-07-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_alter_order_weekday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderWorkDate',
        ),
    ]
