# Generated by Django 4.0.5 on 2022-09-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_remove_case_county_remove_tempcase_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.county'),
        ),
        migrations.AddField(
            model_name='tempcase',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
