# Generated by Django 4.0.5 on 2022-06-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_alter_servant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payinfo',
            name='ATMInfoBankCode',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='ATMInfoExpireDate',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='ATMInfovAccount',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='CVSInfoPayFrom',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='CVSInfoPaymentNo',
        ),
        migrations.RemoveField(
            model_name='payinfo',
            name='CVSInfoPaymentURL',
        ),
    ]
