# Generated by Django 4.0.5 on 2022-08-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_blogcategory_blogpost_blogpostcategoryship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
