# Generated by Django 4.0.5 on 2022-08-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_tempcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcase',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempcase',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
