# Generated by Django 4.0.5 on 2022-08-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_alter_blogpost_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcategoryship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_posts', to='modelCore.blogcategory'),
        ),
        migrations.AlterField(
            model_name='blogpostcategoryship',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_categories', to='modelCore.blogpost'),
        ),
    ]
