# Generated by Django 4.0.4 on 2022-06-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_remove_payinfo_atminfobankcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servantmarkupitemprice',
            name='servant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='servant', to='modelCore.servant'),
        ),
    ]
