# Generated by Django 4.0.5 on 2022-07-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_userstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='newebpay_cityname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
