# Generated by Django 4.0.5 on 2022-08-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_alter_tempcase_city_alter_tempcase_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcase',
            name='increase_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
