# Generated by Django 4.0.5 on 2022-07-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_orderweekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weekday',
        ),
    ]
