# Generated by Django 4.0.5 on 2022-06-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_alter_servantmarkupitemprice_servant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servant',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.RESTRICT, related_name='servant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servantmarkupitemprice',
            name='servant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant'),
        ),
    ]
