# Generated by Django 4.0.5 on 2022-09-28 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_merge_20220928_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcase',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tempcase',
            name='tranfer_info',
        ),
    ]
