# Generated by Django 4.0.5 on 2022-07-08 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0016_remove_order_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderweekday',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_weekday', to='modelCore.order'),
        ),
    ]
