# Generated by Django 4.0.5 on 2022-09-28 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0016_remove_tempcase_address_remove_tempcase_tranfer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelCore.order'),
        ),
        migrations.AddField(
            model_name='systemmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelCore.order'),
        ),
    ]
