# Generated by Django 4.0.5 on 2022-08-31 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0015_alter_blogpostcategoryship_category_and_more'),
        ('modelCore', '0016_tempcase_increase_service'),
    ]

    operations = [
    ]
