# Generated by Django 4.0.5 on 2022-06-23 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='markup_Item_Percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='markup_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='modelCore.markupitem'),
        ),
        migrations.DeleteModel(
            name='ServantMarkupItemPrice',
        ),
    ]
