# Generated by Django 4.0.5 on 2022-08-31 07:25

from django.db import migrations, models
import modelCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_merge_20220831_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=modelCore.models.image_upload_handler),
        ),
    ]
