# Generated by Django 4.0.5 on 2022-07-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_alter_orderweekday_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='increase_percent',
        ),
        migrations.AddField(
            model_name='caseserviceship',
            name='increase_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
