# Generated by Django 4.0.5 on 2022-06-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_recipient_markup_item_percent_recipient_markup_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='markup_Item_Percent',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='markup_item',
        ),
        migrations.AddField(
            model_name='case',
            name='markup_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='modelCore.markupitem'),
        ),
        migrations.CreateModel(
            name='ServantMarkupItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricePercent', models.FloatField(blank=True, default=0, null=True)),
                ('markup_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.markupitem')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant')),
            ],
        ),
    ]
