# Generated by Django 4.0.5 on 2022-07-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_remove_service_increase_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseserviceship',
            name='increase_percent',
        ),
        migrations.AddField(
            model_name='order',
            name='base_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='work_hours',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='OrderIncreaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_percent', models.FloatField(blank=True, default=0, null=True)),
                ('increase_money', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='modelCore.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.service')),
            ],
        ),
    ]
