# Generated by Django 4.0.5 on 2022-10-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_city_namee_alter_case_created_at_alter_case_taken_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='addressCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
