# Generated by Django 4.0.5 on 2022-08-31 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0017_merge_20220831_0250'),
        ('modelCore', '0018_license_ispassed'),
    ]

    operations = [
    ]
