# Generated by Django 4.0.5 on 2022-07-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0019_remove_caseserviceship_increase_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
