# Generated by Django 4.0.5 on 2022-06-23 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0019_remove_recipient_markup_item_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='markup_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servantmarkupitemprice'),
        ),
    ]
