# Generated by Django 4.0.5 on 2022-09-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0018_blogpost_cover_image'),
        ('modelCore', '0019_merge_0017_merge_20220831_0250_0018_license_ispassed'),
    ]

    operations = [
    ]
