# Generated by Django 4.0.5 on 2022-10-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0020_userstore_loginaccount_userstore_memberunified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid_to_servant',
            field=models.BooleanField(default=False),
        ),
    ]
