# Generated by Django 4.0.5 on 2022-07-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0020_order_platform_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='case_offender_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='servant_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
