# Generated by Django 4.0.5 on 2022-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0020_alter_case_markup_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='servant_is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='user_is_rated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='servant_review_createdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='user_review_createdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
