# Generated by Django 4.0.5 on 2022-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0021_alter_review_case_offender_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='case_offender_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='servant_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
