# Generated by Django 4.0.5 on 2022-09-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0021_remove_license_ispassed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='conditions_remark',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='disease_remark',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
