# Generated by Django 4.0.5 on 2022-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0021_order_is_paid_to_servant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=4)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
