# Generated by Django 4.0.5 on 2022-06-23 21:22

from django.db import migrations, models
import modelCore.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0022_user_address_user_email_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=modelCore.models.image_upload_handler),
        ),
    ]
