# Generated by Django 4.0.5 on 2022-09-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0022_alter_case_conditions_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_phone',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_relation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
