# Generated by Django 4.0.5 on 2022-11-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0022_smsverifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='road_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
