# Generated by Django 4.0.5 on 2022-09-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_alter_case_emergencycontact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='conditions_remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='disease_remark',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='emergencycontact_relation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
