# Generated by Django 4.0.5 on 2022-12-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_alter_case_hospital_name_alter_case_road_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewebpayCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
