# Generated by Django 4.0.5 on 2022-06-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0023_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ServantCityAreaShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityarea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.cityarea')),
                ('servant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='modelCore.servant')),
            ],
        ),
    ]
