# Generated by Django 4.0.5 on 2022-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0024_alter_user_line_id_servantcityareaship'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
