# Generated by Django 4.0.5 on 2022-12-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0024_newebpaycity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newebpay_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='newebpay_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='servant_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
