# Generated by Django 4.0.5 on 2022-09-03 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0025_alter_case_conditions_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcase',
            name='servant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='servant_tempcase', to=settings.AUTH_USER_MODEL),
        ),
    ]
