# Generated by Django 4.0.5 on 2022-12-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0025_order_newebpay_money_order_newebpay_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_early_termination',
            field=models.BooleanField(default=False),
        ),
    ]
