# Generated by Django 4.0.5 on 2022-09-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0026_tempcase_servant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcase',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tempcase',
            name='tranfer_info',
            field=models.CharField(default='', max_length=255),
        ),
    ]
