# Generated by Django 4.0.5 on 2023-01-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0026_order_is_early_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='that_time_half_day_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='that_time_hour_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='that_time_one_day_wage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
