# Generated by Django 4.0.5 on 2022-09-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0027_tempcase_address_tempcase_tranfer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcase',
            name='is_booking',
            field=models.BooleanField(default=False),
        ),
    ]
