# Generated by Django 4.0.5 on 2023-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0027_order_that_time_half_day_wage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('unPaid', '未付款'), ('paid', '已付款'), ('canceled', '已取消'), ('cancelOrEarlyEnd', '取消或提前結束')], default='unPaid', max_length=20),
        ),
    ]
