# Generated by Django 4.0.5 on 2022-09-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0028_tempcase_is_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.county'),
        ),
    ]
