# Generated by Django 4.0.5 on 2023-02-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0028_alter_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sent_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
