# Generated by Django 4.0.5 on 2022-09-07 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0029_alter_case_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservicelocation',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='modelCore.county'),
        ),
    ]
