# Generated by Django 4.0.5 on 2023-03-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0030_alter_case_conditions_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iOS_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('android_current_version', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
