# Generated by Django 4.0.5 on 2022-09-08 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0030_alter_userservicelocation_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userserviceship',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='service_ships', to='modelCore.service'),
        ),
    ]
