# Generated by Django 4.0.5 on 2023-09-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0031_appversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='neederName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
