# Generated by Django 4.0.5 on 2022-09-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0032_message_is_read_by_other_side_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField(null=True)),
                ('month_revenue', models.IntegerField(default=0)),
                ('month_cancel_amount', models.IntegerField(default=0)),
                ('month_pay_amount', models.IntegerField(default=0)),
                ('month_refound_amount', models.IntegerField(default=0)),
                ('month_platform_revenue', models.IntegerField(default=0)),
            ],
        ),
    ]
