# Generated by Django 4.0.5 on 2022-09-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0033_monthsummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refound_apply_date',
            new_name='refund_apply_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='refound_money',
            new_name='refund_money',
        ),
    ]
