# Generated by Django 4.0.5 on 2022-09-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0034_rename_refound_apply_date_order_refund_apply_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweekdaytime',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='userweekdaytime',
            name='start_time',
        ),
        migrations.AddField(
            model_name='userweekdaytime',
            name='end_time_hour',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='userweekdaytime',
            name='end_time_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userweekdaytime',
            name='start_time_hour',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userweekdaytime',
            name='start_time_min',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
