# Generated by Django 4.0.5 on 2022-09-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0037_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='taken_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
