# Generated by Django 4.0.5 on 2022-09-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0038_userweekdaytime_end_time_userweekdaytime_sstart_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userweekdaytime',
            old_name='sstart_time',
            new_name='start_time',
        ),
    ]
