# Generated by Django 4.0.5 on 2022-09-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0038_case_taken_at'),
        ('modelCore', '0039_rename_sstart_time_userweekdaytime_start_time'),
    ]

    operations = [
    ]
