# Generated by Django 4.0.5 on 2022-09-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0040_merge_20220912_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicenseshipimage',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_image_ships', to='modelCore.license'),
        ),
    ]
