# Generated by Django 4.0.5 on 2022-09-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0042_assistancepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancepost',
            name='create_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
